### ISSUE TITLE
Error when adding radar with curly quotes

### ISSUE THREAD

**Issue by ZevEisenberg** [timburks/openradar#17]
I tried to submit a radar with curly quotes in the body. I got an error like this when I submitted:

```python
Traceback (most recent call last):
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 716, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/openradar/1.369835338532393896/main.py", line 113, in post
    form_data = urllib.urlencode(form_fields)
  File "/base/data/home/runtimes/python/python_dist/lib/python2.5/urllib.py", line 1259, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 39: ordinal not in range(128)
```

The radar actually submitted anyway, and I was able to modify radars and add curly quotes. It's just adding new ones that seems to cause this problem.

**Comment by timburks** [comment]
I just updated to the Python 2.7 runtime and verified that quotes can be added in Radar descriptions now.  Thanks for your patience.

**Comment by ZevEisenberg** [comment]
Cool! Glad to see the site is still being looked after. Such a great resource.
